version: '3.7'

services:
  smartcarapi:
    build:
      context: .
      target: development
    command: npx nodemon server.js
    environment:
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - .:/srv/smartcarAPI
      - smartcarapi_node_modules:/srv/smartcarAPI/node_modules

volumes:
  smartcarapi_node_modules: